#Build
FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /build
COPY inventory-service/mvnw .
COPY inventory-service/.mvn .mvn
COPY pom.xml .
RUN chmod +x mvnw
COPY inventory-service/pom.xml inventory-service/pom.xml
RUN ./mvnw -f inventory-service/pom.xml dependency:go-offline -B
COPY inventory-service/src inventory-service/src
RUN ./mvnw -f inventory-service/pom.xml clean package -DskipTests


# Run Time
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --chown=appuser:appgroup --from=builder /build/inventory-service/target/*.jar inventory-service.jar
USER appuser
ENTRYPOINT ["java","-jar","inventory-service.jar"]